### ISSUE TITLE
Suggestion for handling of subtitles

### ISSUE THREAD

**Issue by aussiehuddo** [ftc2/radarr_import_subs.sh#1]
Nice script. Haven't tested it yet but looks like what I need for handling RARBG, VXT releases.

Just one note with the renaming to forced, sdh, etc. I notice that RARBG does not follow a strict order when numbering the subtitles. Sometimes a movie has no forced sub but the normal sub is numbered 2. Sometimes its does have a forced sub (like Sonic 2) and the numbers are 11, 12 and 13. i.e. they are not always numbered 2,3,4 in the correct way you have it.

Perhaps a better way to do it for RARBG is to check how many subs there are then:

1. if one then label as normal
2. if two then larger one is sdh, other is normal
3. if three or more then largest is sdh, smallest is forced and others are normal.

I note that this is not perfect. as some films (like Apocalypto (2006)) have only one sub and it is a forced sub. But in this case the user can select it when playing the file.

Let me know what you think.

**Comment by ftc2** [comment]
it's tedious to fully explain the logic of the script in plain-english. for full understanding, try reading the script if you happen to be familiar with bash.

but i updated the readme for clarity. maybe you find this helpful:

---

Subtitles are named according to track numbers in filenames if present.
Examples:
- `1_English.srt` -> `movie.en.forced.srt`
- `2_English.srt` -> `movie.en.srt`
- `3_English.srt` -> `movie.en.sdh.srt`
- `4_English.srt` -> `movie.en.4.srt` (_unknown_ track number preserved in filename)

Track numbers above 3 are considered _unknown_. _Unknown_ track numbers are generally perserved in the filenames for the user's convenience. **Exception:** If only one suitable subs file is found, it is assumed to be track 2 if it has an _unknown_ track number. A subs file without a track number is also assumed to be track 2.

---

i don't think there's a perfect system identifying the subs. you have some good ideas though.

> Perhaps a better way to do it for RARBG is to check how many subs there are then:
> if one then label as normal

yes, that is already done. sorry that the readme was unclear before.

> if two then larger one [i assume you mean larger filesize] is sdh, other is normal

but what if they are actually:
- forced & normal
- normal & director's commentary

> if three or more then largest is sdh, smallest is forced and others are normal.

hm
there can only be one normal sub (track 2) because the final filename becomes `movie.en.srt`. how would you resolve the name for multiple normal subs?
also, what if one of them is actually director's commentary instead?

**Comment by ftc2** [comment]
> looks like what I need for handling RARBG, VXT releases.

just fyi, i personally only use it for VXT rn.

i don't use it for RARBG because bazarr does a decent job of grabbing subs for typical, english-language movies. and the built in feature it has to strip subs of SDH tags (converting them into normal subs basically) is really important to me.

in theory, it makes sense to keep and use the RARBG subs that are included with the torrent, but i absolutely **can't stand it** when normal subs aren't available. sometimes, RARBG only includes SDH subs. :(
so in practice, bazarr usually does OK.

the best solution would be to have an option in my script to trigger bazarr to do post-processing after importing. that way, after RARBG subs are imported, bazarr could strip them of SDH/HI if you set it up that way. but i haven't bothered to add this feature yet. maybe if there's some demand.

**Comment by aussiehuddo** [comment]
You raise some good points. The best solution would be for RARBG to name their subtitles properly to begin with but I don't think that will happen.

My main concern is ensuring that forced subs are included with the files when imported by sonarr, secondary concern is a full sub. Does Bazarr cope well with forced subs?

**Comment by ftc2** [comment]
you meant radarr, right? though i have entertained the idea of making a sonarr version of this.

in case it was unclear, bazarr doesn't import subs included with a release. if they are named appropriately (and not in a subdirectory... hence the existence of my script), radarr will import them if you have it set up to do that. but bazarr actually fetches subs from external providers. usually the subs are good, but sometimes not. i find the most success with relatively mainstream, english language movies. it can attempt to sync the timing by analyzing the movie audio and doing basic speech detection for when people are talking vs not talking. and remove SDH junk like i said before.

i have never tried configuring bazarr to download forced subs though, sorry. personally, i am only interested in 'track 2' subs.

**Comment by aussiehuddo** [comment]
all good. I found another script which can handle RARBG releases but not VXT releases at this stage.
