### ISSUE TITLE
Single SRT with 2 digit number renamed as forced.

### ISSUE THREAD

**Issue by kyedavey** [ftc2/radarr_import_subs.sh#5]
Hi, I just ran into an occasion where a few releases I grabbed had a single SRT that began with a 2 digit number (15) in which it was renamed as forced. I believe it is expected to be renamed as normal given a single SRT file with a number higher than 4. 

Below is one example:

> 2023-11-01 20:10:26.0|Error|radarr_import_subs.sh|Copying subtitle: Subs/15_English.srt --> /movies/Paranormal Activity 3 (2011)/Paranormal Activity 3 (2011) [imdbid-tt1778304] - [Bluray-1080p][AAC 5.1][x265]-RARBG.en.forced.srt

**Comment by ftc2** [comment]
i'm not really using this anymore for multiple reasons: rarbg's dead, i have access to better sources for movies now, and i think radarr can actually natively import subs from subdirs now.

with that said, hm. i wonder if it only parses a single char for the track number, and that's why it thinks it's track 1?

iirc this is a pretty cleanly written script. :)
shouldn't be too hard to troubleshoot if you know bash.

PR welcome if you want to fix it for someone else who might still be using this for some reason, but i'm not really supporting it anymore, sorry.

if it's important, and you're super stuck, maybe i can help you troubleshoot it.

**Comment by kyedavey** [comment]
No worries, I went a different route also, but will do a quick PR for any other using this

**Comment by ftc2** [comment]
thanks for the pr!
